[package]
name = "make_it_fair"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
dotenv = "0.15.0"
log = "0.4.22"
pretty_env_logger = "0.5.0"
tokio = { version = "1.41.1", features = ["full"] }
